config/routes.rb
Rails.application.routes.draw do

  resources :highlights do
  end
  get 'highlights/new'
  get 'highlights/create'
  get 'highlights/update'
  get 'highlights/edit'
  get 'highlights/destroy'
  get 'highlights/index'
  get 'highlights/show'

  devise_for :users

  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :highlights, only: [:index,:create,:show]
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do

      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete
      end

      resources :record

      resources :users, only: [:create]
      match '/users' => 'users#show', :via => :get
      match '/users' => 'users#update', :via => :put
      match '/users' => 'users#destroy', :via => :delete
    end
  end

  root to: "highlights#index"

end

app/models/highlight.rb
class Highlight < ActiveRecord::Base

  validates_presence_of :hostname

  before_save :default_values
  def default_values
    unless self.port
      self.port = self.protocol == "https:"  ? 443 : 80 
    end
  end

  scope :hostname, -> (h) { where hostname: h }
  scope :pathname, -> (p) { where pathname: p }
  scope :port, -> (p) { where port: p }
  scope :protocol, -> (i) { where protocol: i }
  scope :pathname_hash, -> (h) { where pathname_hash: h }
  scope :search, -> (h) { where search: h }

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         # :confirmable,
         # :lockable,
         :timeoutable and :omniauthable

  has_many :highlights
end

app/controllers/api/v1/highlights_controller.rb
class Api::V1::HighlightsController < ApplicationController
  before_action :set_highlight, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user! , :except => [:index, :show]
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }



  # GET /highlights
  # GET /highlights.json
  def index
    @highlights = Highlight.where(nil)
    @highlights = @highlights.hostname(params[:hostname]) if params[:hostname].present?
    @highlights = @highlights.pathname(params[:pathname]) if params[:pathname].present?
    @highlights = @highlights.port(params[:port]) if params[:port].present?
    @highlights = @highlights.protocol(params[:protocol]) if params[:protocol].present?
    @highlights = @highlights.search(params[:search]) if params[:search].present?
    @highlights = @highlights.pathname_hash(params[:pathname_hash]) if params[:pathname_hash].present?
    render "highlights/index"
  end

  # GET /highlights/1
  # GET /highlights/1.json
  def show
    render "highlights/show"
  end

  # GET /highlights/new
  #def new
  #  @highlight = Highlight.new(user: current_user)
  #end

  # GET /highlights/1/edit
  def edit
  end

  # POST /highlights
  # POST /highlights.json
  def create
    #puts "create ..."
    puts highlight_params
    @highlight = Highlight.new(highlight_params)
    @highlight.user = current_user

    respond_to do |format|
      if @highlight.save
        format.json { render "highlights/show" , status: :created, location: @highlight }
      else
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highlights/1
  # PATCH/PUT /highlights/1.json
  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        #format.html { redirect_to @highlight, notice: 'Highlight was successfully updated.' }
        format.json { render :show, status: :ok, location: @highlight }
      else
        #format.html { render :edit }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highlights/1
  # DELETE /highlights/1.json
  def destroy
    @highlight.destroy
    respond_to do |format|
      #format.html { redirect_to highlights_url, notice: 'Highlight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      #params.require(:highlight).permit(:selector, :text, :host, :port ,:path, :start_offset, :end_offset)
      p = JSON.parse(params[:highlight])
      puts "highlight_params"
      #puts p
      p.slice( 'selector', 'text', 'hostname', 'port' , 'pathname' ,'search', 'pathname_hash', 'protocol', 'start_offset', 'end_offset', 'tag_name' )
      #params.require(:highlight).permit( 'selector', 'text', 'hostname', 'port' , 'pathname' ,'search', 'pathname_hash', 'protocol', 'start_offset', 'end_offset' )

    end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Devise::SessionsController

   protect_from_forgery with: :null_session, :if => Proc.new { |c| c.request.format == 'application/vnd.myapp.v1' }

    def create
      warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
      render :json => { :info => "Logged in", success: true, :user => current_user }, :status => 200
    end

    def destroy
      warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
      sign_out
      render :json => { :info => "Logged out", success: true }, :status => 200
    end

    def failure
      render :json => { :error => "Login Credentials Failed" }, :status => 401
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_action :set_highlight, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!


  # GET /highlights
  # GET /highlights.json
  def index
    @highlights = current_user.highlights.page(params['page']).per_page(5)
  end

  # GET /highlights/1
  # GET /highlights/1.json
  def show
  end

  # GET /highlights/new
  def new
    @highlight = Highlight.new(user: current_user)
  end

  # GET /highlights/1/edit
  def edit
  end

  # POST /highlights
  # POST /highlights.json
  def create
    @highlight = Highlight.new(highlight_params)

    respond_to do |format|
      if @highlight.save
        format.html { redirect_to @highlight, notice: 'Highlight was successfully created.' }
        format.json { render :show, status: :created, location: @highlight }
      else
        format.html { render :new }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highlights/1
  # PATCH/PUT /highlights/1.json
  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        format.html { redirect_to @highlight, notice: 'Highlight was successfully updated.' }
        format.json { render :show, status: :ok, location: @highlight }
      else
        format.html { render :edit }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highlights/1
  # DELETE /highlights/1.json
  def destroy
    @highlight.destroy
    respond_to do |format|
      format.html { redirect_to highlights_url, notice: 'Highlight was successfully destroyed.' }
      format.json { head :no_content }
    end

  # POST /highlight/query
  # POST /highlight/query.json
  def query

  end 

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      params.require(:highlight).permit(:selector, :text, :hostname, :port ,:pathname, :pathname_hash, :search , :protocol , :start_offset, :end_offset , :tag_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/highlights/_form.html.erb
<%= simple_form_for @highlight, :html => { :class => "form-horizontal highlight" } do |f| %>

    <%= f.error_notification %>
    <%= f.input :text %>
    <%= f.input :hostname %>
    <%= f.input :pathname %>
    <%= f.input :protocol %>
    <%= f.input :port %>
    <%= f.input :search %>
    <%= f.input :pathname_hash %>
    <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
    <%= f.error :base %>
    <%= f.button :submit %>

<% end %>

app/views/highlights/create.html.erb
<h1>Highlights#create</h1>
<p>Find me in app/views/highlights/create.html.erb</p>

app/views/highlights/destroy.html.erb
<h1>Highlights#destroy</h1>
<p>Find me in app/views/highlights/destroy.html.erb</p>

app/views/highlights/edit.html.erb
<%- model_class = Highlight -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/highlights/index.html.erb
<%- model_class = Highlight -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:hostname) %></th>
      <th><%= model_class.human_attribute_name(:pathname) %></th>
      <th><%= model_class.human_attribute_name(:search) %></th>
      <th><%= model_class.human_attribute_name(:pathname_hash) %></th>
      <th><%= model_class.human_attribute_name(:port) %></th>
      <th><%= model_class.human_attribute_name(:protocol) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @highlights.each do |highlight| %>
      <tr>
        <td><%= link_to highlight.id, highlight_path(highlight) %></td>
        <td><%= highlight.user_id %></td>
        <td><%= highlight.text %></td>
        <td><%= highlight.hostname %></td>
        <td><%= highlight.pathname %></td>
        <td><%= highlight.search %></td>
        <td><%= highlight.pathname_hash %></td>
        <td><%= highlight.port %></td>
        <td><%= highlight.protocol %></td>
        <td><%=l highlight.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_highlight_path(highlight), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      highlight_path(highlight),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tr>
    <td span="5">
        <%= will_paginate @highlights %>
    </td>
  </tr>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_highlight_path,
            :class => 'btn btn-primary' %>

app/views/highlights/new.html.erb
<%- model_class = Highlight -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/highlights/show.html.erb
<%- model_class = Highlight -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @highlight.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:selector) %>:</strong></dt>
  <dd><%= @highlight.selector %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @highlight.text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hostname) %>:</strong></dt>
  <dd><%= @highlight.hostname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pathname) %>:</strong></dt>
  <dd><%= @highlight.pathname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:search) %>:</strong></dt>
  <dd><%= @highlight.search %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pathname_hash) %>:</strong></dt>
  <dd><%= @highlight.pathname_hash %></dd>
  <dt><strong><%= model_class.human_attribute_name(:port) %>:</strong></dt>
  <dd><%= @highlight.port %></dd>
  <dt><strong><%= model_class.human_attribute_name(:protocol) %>:</strong></dt>
  <dd><%= @highlight.protocol %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_offset) %>:</strong></dt>
  <dd><%= @highlight.start_offset %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_offset) %>:</strong></dt>
  <dd><%= @highlight.end_offset %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tag_name) %>:</strong></dt>
  <dd><%= @highlight.tag_name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              highlights_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_highlight_path(@highlight), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              highlight_path(@highlight),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/highlights/update.html.erb
<h1>Highlights#update</h1>
<p>Find me in app/views/highlights/update.html.erb</p>

app/views/home/index.erb
<div ng-app="HilititApp">
  asdfaf
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">
  <% if user_signed_in? %>

      <li class="navbar-link">
        <%= link_to t('Highlights') , highlights_path %>
      </li>
      <li class="navbar-link">
        <%= link_to t("Edit #{current_user.email} profile") , edit_user_registration_path %>
      </li>
      <li class="navbar-link">
        <%= link_to t("Logout") , destroy_user_session_path, method: :delete %>
      </li>

    <% else %>

      <li class="navbar-link">
        <%= link_to t("Signup") , new_user_registration_path  %>
      </li>
      <li class="navbar-link">
        <%= link_to t("Login") , new_user_session_path %>
      </li>
    <% end %>

    </ul>
</nav>

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logged In [click to logout]", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeHighlight.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <!-- nav bar -->

  <%= render 'layouts/nav' %>


  <% flash.each do | name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible rails-alert-name-<%=name%>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= msg %>
    </div>
  <% end %>

  <!--
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  -->

  <div class="container">
    <div class="row">
      <div class="col-md-2"><h2>About Us</h2></div>
      <div class="col-md-8"><%= yield %></div>
    </div>
  </div>


</body>
</html>